/**
 * Portal PDF Security — post-processing layer for portal-downloaded documents.
 *
 * Adds to the official PDF generated by PrimeDocument:
 *   1. "PORTAL COPY" watermark (diagonal, semi-transparent, every page)
 *   2. Document metadata indicating portal origin
 *   3. ViewerPreferences (display hints for compliant viewers)
 *
 * This layer is ONLY applied when source === 'portal'. ERP staff/shop
 * documents bypass this entirely — they receive the raw PrimeDocument output.
 *
 * Uses pdf-lib (pure JS, no native dependencies) for all post-processing.
 *
 * NOTE ON PDF PERMISSIONS:
 * pdf-lib does not natively support PDF encryption/permissions. True PDF
 * permission flags (modification, copying, annotation restrictions) require
 * either:
 *   - qpdf (external CLI tool, not installed)
 *   - Ghostscript (external CLI tool, not installed)
 *   - Custom encryption dictionary implementation
 *
 * The watermark + metadata combination provides:
 *   - Clear visual provenance (every page says "PORTAL COPY")
 *   - Tamper evidence (removing the watermark requires PDF editing)
 *   - Metadata trail (portal origin recorded in document properties)
 *
 * If qpdf or Ghostscript is installed in the future, this module can be
 * extended to apply true PDF permission flags.
 */

const { PDFDocument, rgb, degrees, StandardFonts, ViewerPreferences, NonFullScreenPageMode, ReadingDirection, PrintScaling, Duplex } = require('pdf-lib');

// ─── Watermark Configuration ────────────────────────────────────────────────

const WATERMARK_PRIMARY = 'PORTAL COPY';
const WATERMARK_SECONDARY = 'DOWNLOADED FROM CUSTOMER PORTAL';

/**
 * Add watermark text to every page of the PDF.
 * Embeds Helvetica for consistent rendering across viewers.
 *
 * The watermark is:
 *   - Diagonal (-35 degrees) for visibility
 *   - Semi-transparent (opacity 0.08) to preserve readability
 *   - Centered on every page
 *   - Uses bold font for primary text, regular for secondary
 */
async function addWatermark(pdfBytes) {
  const pdfDoc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });

  // Embed standard fonts for the watermark text
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const pages = pdfDoc.getPages();
  for (const page of pages) {
    const { width, height } = page.getSize();
    const centerX = width / 2;
    const centerY = height / 2;

    // Primary watermark — large, semi-transparent diagonal text
    page.drawText(WATERMARK_PRIMARY, {
      x: centerX - 110,
      y: centerY + 8,
      size: 36,
      font: helveticaBold,
      color: rgb(0, 0, 0),
      opacity: 0.08,
      rotate: degrees(-35),
    });

    // Secondary watermark — smaller
    page.drawText(WATERMARK_SECONDARY, {
      x: centerX - 145,
      y: centerY - 22,
      size: 11,
      font: helvetica,
      color: rgb(0, 0, 0),
      opacity: 0.07,
      rotate: degrees(-35),
    });
  }

  return pdfDoc.save({ useObjectStreams: false });
}

// ─── Document Metadata ──────────────────────────────────────────────────────

/**
 * Set document metadata indicating portal origin.
 * These appear in the PDF's Properties dialog in most viewers.
 */
async function applyMetadata(pdfBytes) {
  const pdfDoc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });

  // Set creator/producer metadata
  // Note: pdf-lib internally sets Producer to its own library name.
  // We set Creator which is the primary authoring tool indicator.
  pdfDoc.setCreator('Prime ERP — Customer Portal');

  // Subject indicates portal source
  const existingSubject = pdfDoc.getSubject() || '';
  pdfDoc.setSubject(
    existingSubject
      ? `${existingSubject} [Source: Customer Portal]`
      : 'Customer Portal Download'
  );

  // Set ViewerPreferences for compliant viewers
  // These are display hints, not security restrictions, but they signal
  // the document's intended use.
  try {
    const viewerPrefs = pdfDoc.catalog.getOrCreate(pdfDoc.context.obj('ViewerPreferences'));
    // Set print scaling to none (consistent appearance)
    viewerPrefs.set(pdfDoc.context.obj('PrintScaling'), pdfDoc.context.obj('None'));
    // Set non-full-screen page mode
    viewerPrefs.set(pdfDoc.context.obj('NonFullScreenPageMode'), pdfDoc.context.obj('UseNone'));
    // Set reading direction (left-to-right)
    viewerPrefs.set(pdfDoc.context.obj('Direction'), pdfDoc.context.obj('L2R'));
  } catch (_) {
    // ViewerPreferences is optional — don't fail if the catalog structure is unusual
  }

  return pdfDoc.save();
}

// ─── Combined Portal Security ───────────────────────────────────────────────

/**
 * Apply full portal security treatment to a PDF buffer:
 *   1. Watermark on every page
 *   2. Portal-origin metadata
 *   3. ViewerPreferences (display hints)
 *
 * @param {Buffer} pdfBuffer - The raw PDF bytes from PrimeDocument
 * @returns {Buffer} Secured PDF bytes
 */
async function securePortalPdf(pdfBuffer) {
  // Step 1: Add watermark
  let bytes = await addWatermark(pdfBuffer);

  // Step 2: Apply metadata + viewer preferences
  bytes = await applyMetadata(bytes);

  return Buffer.from(bytes);
}

module.exports = {
  securePortalPdf,
  addWatermark,
  applyMetadata,
  WATERMARK_PRIMARY,
  WATERMARK_SECONDARY,
};
